Hair-Style-Recommendation-System-main/hairRecommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hair_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hair-Style-Recommendation-System-main/hair_app/urls.py
from django.urls import path
from . import views

app_name = 'hair_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutus/', views.aboutus, name='aboutus'),
]

Hair-Style-Recommendation-System-main/hair_app/models.py
from django.db import models

# Create your models here.

Hair-Style-Recommendation-System-main/hair_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from PIL import Image
from keras.preprocessing import image
import numpy as np
import tensorflow as tf
from keras.models import load_model
import keras.backend as K
from . import red_emo_hair
import dlib
from math import hypot
import cv2

# Create your views here.

out_dict = {'Heart': 0, 'Oblong': 1, 'Oval': 2, 'Round': 3, 'Square': 4}

li = list(out_dict.keys())

def index(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        m = str(filename)
        K.clear_session()
        im = Image.open("{}/".format(settings.MEDIA_ROOT) + m)
        j = im.resize((256, 256),)
        l = "predicted.jpg"
        j.save("{}/".format(settings.MEDIA_ROOT) + l)
        file_url = fs.url(l)
        mod = load_model('model1.hdf5', compile=False)
        
        img1 = cv2.imread('C:\\hairRecommendation\\media\\' + filename)

        detector = dlib.get_frontal_face_detector()
        face = detector(img1)

        img = image.load_img(myfile, target_size=(32, 32))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        preds = mod.predict(x)
        d = preds.flatten()
        j = d.max()

        #For the template fitting part, we should import and export the image with the cv2 methods
        processed_image = red_emo_hair.process_red_hair(img1)
        cv2.imwrite("C:\\hairRecommendation\\media\\processed.jpg", processed_image)
        
        # processed_image = Image.fromarray(processed_image)
        # processed_image.save("C:\\Users\\Laravel\\sailoonai\\manish\\djangoMedia\\media\\processed.jpg")
        new_url = fs.url('processed.jpg')

        for index, item in enumerate(d):
            if item == j:
                result = li[index]
                return render(request, "index.html", {
                                'result': result, 'file_url': file_url, 'new_url': new_url, 'face': face })
    return render(request, "index.html")

def aboutus(request):
    return render(request, 'aboutus.html')

    

Hair-Style-Recommendation-System-main/hair_app/templates/aboutus.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styleeeee.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'imgs.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <title>About Us</title>
    
</head>

<body>
    <div class="header-bar-warp d-flex">
        <h3 style='color: white; font-family: cursive; font-style: italic; font-size:26px;'><a style="color: white;"
                href="{% url 'hair_app:index' %}">AI Based HairStyle Recommender</a></h3>

        <nav class="top-nav-area w-75">

            <!-- Menu -->
            <ul class="main-menu primary-menu">
                <li><a href="{% url 'hair_app:index' %}"><strong>Home</strong></a></li>
                <li><a href="#"><strong>Facial Features</strong></a></li>
                <li><a href="#"><strong>Gallery</strong></a></li>
                <li><a href="{% url 'hair_app:aboutus' %}"><strong>About Us</strong></a></li>

            </ul>
        </nav>


    </div>
    <br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/niten.jpg' %}" alt="Niten" style="width:100%; height:400px;">
                <div class="container">
                    <div class="container">
                        <h2>Niten Lama</h2>


                        <p>nitenlama46@gmail.com</p>
                        <p></p>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/manish.jpg' %}" alt="Manish" style="width:100%; height:400px;">
                <div class="container">
                    <h2>Manish Bhurtel</h2>
                 
                    
                    <p>manish.bhurtel09@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/aashma.jpg' %}" alt="Aashma" style="width:100%;height:400px;">
                <div class="container">
                        <h2>Aashma Uprety</h2>
                        

                        <p>aashmauprety@gmail.com</p>
               
                    </div>
            </div>
        </div>
    </div>
    </body>
    </html>

Hair-Style-Recommendation-System-main/hair_app/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
<link rel="stylesheet" href="{% static 'styleeeee.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <title>HairStyleRecommender</title>
  </head>
  <body>
      <div class="header-bar-warp d-flex">
        <h3 style='color: white; font-family: cursive; font-style: italic; font-size:26px;'><a style="color: white;" href="{% url 'hair_app:index' %}">
            AI Based HairStyle Recommender</a></h3>
        
        <nav class="top-nav-area w-75">
          
          <!-- Menu -->
          <ul class="main-menu primary-menu">
            <li><a href="{% url 'hair_app:index' %}"><strong>Home</strong></a></li>
            <li><a href="#"><strong>Facial Features</strong></a></li>
            <li><a href="#"><strong>Gallery</strong></a></li>
            <li><a href="{% url 'hair_app:aboutus' %}"><strong>About Us</strong></a></li>
            
          </ul>
        </nav>
        
        
      </div>
      
    
     <br><br><br>
      <div class="container">
          <form method="post" id="fileform" enctype="multipart/form-data">
            {% csrf_token %} 
            <div class="file-upload">
              <div class="file-select">
                  <div class="file-select-button" id="fileName"><h6>Upload Image</h6></div>
                <div class="file-select-name" id="noFile">No Image Uploaded...</div> 
                <input id="chooseFile" type="file" name="myfile">
              </div>
              <br><br>
           </div>
           <br>
           <div class="container">
              <div class="row">
                <div class="col-sm-5">
                    
                </div>
                
                <div class="col-sm-4">
                    <button id="sub" class="btn btn-primary btn-lg" type="submit">Recommend</button>
                </div>
                 
              </div>
           </div>
           
          </form>
      </div>
      <br>
      
      <div class="container">
        <div class="row">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-4">
                  {% if file_url %}
                  {% if face %}
                    <h1 id='filename'><strong>{{ result }}</strong></h1>
                  <img src={{ file_url }}>
            </div>
        </div>
        <div class="row">
            {% if result == "Round" %}
                    <h2><span style="color: white"> You have a Round face. Following Hairstyles are recommended for you: </span></h2>

                    <div class="col-md-3">
                        <img src="{% static 'images/Round Hairstyles/asymmetric bob.jpeg' %}" alt="Round1" height="350" width="300">
                    </div>

                    <div class="col-md-3">
                            <img src="{% static 'images/Round Hairstyles/long bob.png' %}" alt="Round2" height="350" width="400">
                    </div>

                    <div class="col-md-3">
                        <img src="{% static 'images/Round Hairstyles/long soft waves.jpg' %}" alt="Round3" height="350" width="400">
                    </div>

                    <div class="col-md-3">
                        <img src="{% static 'images/Round Hairstyles/short waves with long bangs.jpg' %}" alt="Round4" height="350" width="400">
                    </div>

                {% elif result == "Square" %}
                <h2><span style="color: white"> You have a Square face.&nbsp;Following Hairstyles are recommended for you: </span></h2>

                    <div class="col-md-3">
                            <img src="https://stylesatlife.com/wp-content/uploads/2019/07/Front-Fringes.jpg" alt="Square1" height="350" width="400">

                    </div>
                    <div class="col-md-3">
                         <img src="https://stylesatlife.com/wp-content/uploads/2015/09/Hairstyles-For-Oval-Faces-13.jpg" alt="Square2" height="350" width="400">
                    </div>
                    <div class="col-md-3">
                        <img src="https://stylesatlife.com/wp-content/uploads/2015/09/Hairstyles-For-Oval-Faces-14.jpg" alt="Square3" height="350" width="400">
                    </div>
                    <div class="col-md-3">
                        <img src="https://stylesatlife.com/wp-content/uploads/2015/09/Hairstyles-For-Oval-Faces-16.jpg" alt="Square4" height="350" width="400">
                    </div>


                {% elif result == "Oval" %}
                    <h2><span style="color: white"> You have an Oval face.&nbsp;Following Hairstyles are recommended for you: </span></h2>

                        <div class="col-md-3">
                             <img src="https://www.byrdie.com/thmb/3KaeKfdlVA6Y-IDIwBcV0dlk07A=/800x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/jenna-elfman-56a087843df78cafdaa276f0.jpg" alt="Oval1" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                             <img src="https://www.byrdie.com/thmb/jPfiAElkNZ8vBcWHL1a-2LVpjx0=/800x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/platinum-blond-shag-57befad43df78cc16e064117.jpg" alt="Oval2" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="https://www.byrdie.com/thmb/lfXlMg1w01HUGFa1bFG_BjNLzqA=/800x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/julianne-hough-blonde-hair-56a0849f3df78cafdaa2612e.jpg" alt="Oval3" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="" alt="Oval4" height="350" width="400">
                        </div>

                {% elif result == "Oblong" %}
                    <h2><span style="color: white"> You have an Oblong face. Following Hairstyles are recommended for you: </span></h2>

                        <div class="col-md-3">
                             <img src= "{% static 'images/Oblong Hairstyles/chin length bob.jpg'%}" alt="Oblong1" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                             <img src="{% static 'images/Oblong Hairstyles/pixie with short bangs.jpg'%}" alt="Oblong2" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="{% static 'images/Oblong Hairstyles/retro curls.jpg'%}" alt="Oblong3" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="{% static 'images/Oblong Hairstyles/soft waves.jpg'%}" alt="Oblong4" height="350" width="400">
                        </div>

                {% else %}
                    <h2><span style="color: white"> You have a Heart face. Following Hairstyles are recommended for you: </span></h2>

                        <div class="col-md-3">
                             <img src="{{ new_url }}" alt="Heart1" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                             <img src="https://www.byrdie.com/thmb/jPfiAElkNZ8vBcWHL1a-2LVpjx0=/800x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/platinum-blond-shag-57befad43df78cc16e064117.jpg" alt="Heart2" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="https://www.byrdie.com/thmb/lfXlMg1w01HUGFa1bFG_BjNLzqA=/800x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/julianne-hough-blonde-hair-56a0849f3df78cafdaa2612e.jpg" alt="Heart3" height="350" width="400">
                        </div>
                        <div class="col-md-3">
                            <img src="{% static 'images/Heart Hairstyles/long curls.jpg' %}" alt="Heart4" height="350" width="400">
                        </div>

                {% endif %}
                {% else %}
                <br> <h2 style = "color:aliceblue; text-align: center">Please Insert a valid photo</h2>
                {% endif %}
            {% else %}
                  <br>
                    <h1 style="color:white;">No Preview</h1>
                {% endif %}
        </div>
        </div>
      
      
      
    
  </body>
 
</html>